---
# Kafka cluster by landoop
version: '3'
services:
  kafka-cluster:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: kafka-cluster     # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
    - "42181:2181"                 # Zookeeper
    - "43030:3030"                 # Landoop UI
    - "48081-48083:8081-8083"       # REST Proxy, Schema Registry, Kafka Connect ports
    - "49581-49585:9581-9585"       # JMX Ports
    - "49092:9092"                 # Kafka Broker